# To get started with Dependabot (dependency bot by github) version updates, 
# you'll need to specify which package ecosystems to update and where the 
# package manifests are located.

# Please see the documentation for all configuration options:
# https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates

# Schedule: daily | weekly | monthly
# https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#scheduleinterval

# Package-Ecosystem:
# https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#package-ecosystem

version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - <MainGitHubUserNameForPullRequests>

  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - <MainGitHubUserNameForPullRequests>

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - <MainGitHubUserNameForPullRequests>

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - <MainGitHubUserNameForPullRequests>

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - <MainGitHubUserNameForPullRequests>

  - package-ecosystem: "yarn"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - <MainGitHubUserNameForPullRequests>
  
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - <MainGitHubUserNameForPullRequests>
